#############################################################################
# Makefile for building: Paraft
# Generated by qmake (2.01a) (Qt 4.8.2) on: Mon Jun 18 16:27:25 2012
# Project:  Paraft.pro
# Template: app
# Command: /usr/local/Cellar/qt/4.8.2/bin/qmake -spec /usr/local/Cellar/qt/4.8.2/mkspecs/unsupported/macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug -o Makefile Paraft.pro
#############################################################################

####### Compiler, tools and options

CC            = /usr/local/Cellar/open-mpi/1.4.5/bin/mpicc
CXX           = /usr/local/Cellar/open-mpi/1.4.5/bin/mpic++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Cellar/qt/4.8.2/mkspecs/unsupported/macx-clang -I. -I/usr/local/Cellar/qt/4.8.2/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.2/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.2/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.2/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.2/include -I/usr/local/Cellar/open-mpi/1.4.5/include -I/usr/include -I. -F/usr/local/Cellar/qt/4.8.2/lib
LINK          = clang++
LFLAGS        = -headerpad_max_install_names -arch x86_64
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/4.8.2/lib -L/usr/local/Cellar/qt/4.8.2/lib -L/usr/local/Cellar/open-mpi/1.4.5/lib -lmpi_cxx -lmpi -lopen-rte -lopen-pal -lutil -framework QtGui -L/usr/X11/lib -L/usr/local/Cellar/qt/4.8.2/lib -F/usr/local/Cellar/qt/4.8.2/lib -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/Cellar/qt/4.8.2/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Main.cpp 
OBJECTS       = Main.o
DIST          = /usr/local/Cellar/qt/4.8.2/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.2/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/debug.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/declarative_debug.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/include_source_dir.prf \
		Paraft.pro
QMAKE_TARGET  = Paraft
DESTDIR       = 
TARGET        = Paraft

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		x86_64 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Paraft.pro  /usr/local/Cellar/qt/4.8.2/mkspecs/unsupported/macx-clang/qmake.conf /usr/local/Cellar/qt/4.8.2/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.2/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/debug.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/declarative_debug.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/include_source_dir.prf \
		/usr/local/Cellar/qt/4.8.2/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt/4.8.2/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /usr/local/Cellar/qt/4.8.2/mkspecs/unsupported/macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug -o Makefile Paraft.pro
/usr/local/Cellar/qt/4.8.2/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/4.8.2/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/4.8.2/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/4.8.2/mkspecs/common/gcc-base-macx.conf:
/usr/local/Cellar/qt/4.8.2/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/4.8.2/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/4.8.2/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/dwarf2.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/debug.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/x86_64.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/declarative_debug.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/lex.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/include_source_dir.prf:
/usr/local/Cellar/qt/4.8.2/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt/4.8.2/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Cellar/qt/4.8.2/mkspecs/unsupported/macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug -o Makefile Paraft.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Paraft1.0.0 || $(MKDIR) .tmp/Paraft1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Paraft1.0.0/ && $(COPY_FILE) --parents Main.cpp .tmp/Paraft1.0.0/ && (cd `dirname .tmp/Paraft1.0.0` && $(TAR) Paraft1.0.0.tar Paraft1.0.0 && $(COMPRESS) Paraft1.0.0.tar) && $(MOVE) `dirname .tmp/Paraft1.0.0`/Paraft1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Paraft1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

Main.o: Main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Main.o Main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

