######################################################################
# Automatically generated by qmake (2.01a) Mon May 4 11:13:00 2009
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += debug_and_release staticlib

# Input
HEADERS += option.h \
	optionmanager.h \
	optiongroupbox.h \
	optionslider.h
SOURCES += option.cpp \
	optionmanager.cpp \
	optiongroupbox.cpp \
	optionslider.cpp
